# Generated by Django 4.2.1 on 2023-05-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_alter_result_questions"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="answers",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_true", True)),
                fields=("question",),
                name="unique_correct_option",
            ),
        ),
    ]
